name: Java CI with Maven

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn install && cd dist && mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable-jar
          path: target/*.jar